name: 📦 Compile binary
inputs:
  target:
    required: true
  binary:
    required: true
  setup:
    required: true
  build:
    required: true
  skippable:
    required: true
runs:
  using: 'composite'
  steps:
    - name: 🛒 Get source code
      shell: bash
      uses: actions/checkout@v4

    - name: 💻 Run setup script
      shell: bash
      working-directory: ./binary
      run: ${{ inputs.setup }}

    - name: 🔨 Compile binary
      shell: bash
      working-directory: ./binary
      run: ${{ inputs.build }}

    - name: 📂 Move binary to package
      shell: bash
      working-directory: ./package
      run: npm run get-binaries

    - name: 🔬 Run example testing
      shell: bash
      working-directory: ./example
      run: |
        npm install
        npm run build
        npm run test
      continue-on-error: ${{ inputs.skippable }}

    - name: 📂 Upload binary
      shell: bash
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.ref_name }}.${{ inputs.binary }}
        path: ./binary/target/${{ inputs.target }}/${{ inputs.binary }}
      continue-on-error: ${{ inputs.skippable }}