services:

  binary-prebuild:
    build:
      context: ./binary
      target: binary-prebuild

  binary:
    build:
      context: ./binary
    depends_on:
      - binary-prebuild

  package:
    build:
      context: ./package 
    depends_on:
      - binary

  ui:
    build: ui
    ports:
      - "127.0.0.1:26023:26023"

  website:
    build: website
    ports:
      - "25032:25032"
    depends_on:
      - ui
      - spec

  spec:
    build: spec
    depends_on:
      - package