on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      target:
        required: true
        type: string
      binary:
        required: true
        type: string
      setup:
        required: true
        type: string
      build:
        required: true
        type: string
      skippable:
        required: true
        type: string

jobs:
  compile:
    name: 📦 Compile
    runs-on: ${{ inputs.os }}
    steps:
      - name: 🛒 Get source code
        uses: actions/checkout@v4

      - name: 💻 Run setup script
        working-directory: ./binary
        run: ${{ inputs.setup }}

      - name: 🔨 Compile binary
        working-directory: ./binary
        run: ${{ inputs.build }}

      - name: 📂 Move binary to package
        working-directory: ./package
        run: npm run get-binaries

      - name: 🔬 Run example testing
        working-directory: ./example
        run: |
          npm install
          npm run build
          npm run test
        continue-on-error: ${{ inputs.skippable }}

      - name: 📂 Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}.${{ inputs.binary }}
          path: ./binary/target/${{ inputs.target }}/${{ inputs.binary }}
        continue-on-error: ${{ inputs.skippable }}